### ISSUE TITLE
Deleting a resource causes panic and crashes ECR controller 

### ISSUE THREAD

**Issue by nithu0115** [aws/aws-controllers-k8s#166]
**Describe the bug**
A concise description of what the bug is.
#165 while testing create scenario, I have delete and recreate the Repository resource multiple times which resulted in a panic instead of safe deletion causing ECR controller to crash. 

```
      RepositoryUri: "<account ID>.dkr.ecr.us-west-2.amazonaws.com/testing"
    }]
}Observed event is arn:aws:ecr:us-west-2:<account ID>:repository/testing 
E0811 15:51:44.335897    5234 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 139 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x21e94c0, 0x3253ed0)
        /Users/nithmu/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /Users/nithmu/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:48 +0x82
panic(0x21e94c0, 0x3253ed0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/aws/aws-controllers-k8s/pkg/runtime.(*reconciler).sync(0xc00011e100, 0x27224e0, 0xc0000d6008, 0x27226e0, 0xc00025b580, 0x2730200, 0xc00064e6a0, 0x0, 0x0)
        /Users/nithmu/go/src/github.com/aws/aws-controllers-k8s/pkg/runtime/reconciler.go:132 +0x1f1
github.com/aws/aws-controllers-k8s/pkg/runtime.(*reconciler).reconcile(0xc00011e100, 0xc0000d7940, 0x7, 0xc0000d7930, 0x5, 0x1e07d5f0, 0x6b23e97a5b8)
        /Users/nithmu/go/src/github.com/aws/aws-controllers-k8s/pkg/runtime/reconciler.go:110 +0x391
github.com/aws/aws-controllers-k8s/pkg/runtime.(*reconciler).Reconcile(0xc00011e100, 0xc0000d7940, 0x7, 0xc0000d7930, 0x5, 0xc00007acb0, 0xc0004ac120, 0xc0004aa128, 0x26f7300)
        /Users/nithmu/go/src/github.com/aws/aws-controllers-k8s/pkg/runtime/reconciler.go:84 +0x57
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000184000, 0x2242200, 0xc00012e760, 0x1040100)
        /Users/nithmu/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000184000, 0x0)
        /Users/nithmu/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000184000)
        /Users/nithmu/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000300670)
        /Users/nithmu/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000300670, 0x26e8720, 0xc0001b5350, 0x1, 0xc0000be1e0)
        /Users/nithmu/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000300670, 0x3b9aca00, 0x0, 0x1, 0xc0000be1e0)
        /Users/nithmu/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133 +0xaa
k8s.io/apimachinery/pkg/util/wait.Until(0xc000300670, 0x3b9aca00, 0xc0000be1e0)
        /Users/nithmu/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /Users/nithmu/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:193 +0x328
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x204da51]

goroutine 139 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /Users/nithmu/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:55 +0x105
panic(0x21e94c0, 0x3253ed0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/aws/aws-controllers-k8s/pkg/runtime.(*reconciler).sync(0xc00011e100, 0x27224e0, 0xc0000d6008, 0x27226e0, 0xc00025b580, 0x2730200, 0xc00064e6a0, 0x0, 0x0)
        /Users/nithmu/go/src/github.com/aws/aws-controllers-k8s/pkg/runtime/reconciler.go:132 +0x1f1
github.com/aws/aws-controllers-k8s/pkg/runtime.(*reconciler).reconcile(0xc00011e100, 0xc0000d7940, 0x7, 0xc0000d7930, 0x5, 0x1e07d5f0, 0x6b23e97a5b8)
        /Users/nithmu/go/src/github.com/aws/aws-controllers-k8s/pkg/runtime/reconciler.go:110 +0x391
github.com/aws/aws-controllers-k8s/pkg/runtime.(*reconciler).Reconcile(0xc00011e100, 0xc0000d7940, 0x7, 0xc0000d7930, 0x5, 0xc00007acb0, 0xc0004ac120, 0xc0004aa128, 0x26f7300)
        /Users/nithmu/go/src/github.com/aws/aws-controllers-k8s/pkg/runtime/reconciler.go:84 +0x57
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000184000, 0x2242200, 0xc00012e760, 0x1040100)
        /Users/nithmu/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000184000, 0x0)
        /Users/nithmu/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000184000)
        /Users/nithmu/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000300670)
        /Users/nithmu/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000300670, 0x26e8720, 0xc0001b5350, 0x1, 0xc0000be1e0)
        /Users/nithmu/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000300670, 0x3b9aca00, 0x0, 0x1, 0xc0000be1e0)
        /Users/nithmu/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133 +0xaa
k8s.io/apimachinery/pkg/util/wait.Until(0xc000300670, 0x3b9aca00, 0xc0000be1e0)
        /Users/nithmu/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /Users/nithmu/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:193 +0x328
exit status 2
```

**Steps to reproduce**
Steps mentioned on #165 +
`Kubectl delete Repository tetsg`

**Expected outcome**
It should delete the Repository resource and not panic/crash 

**Environment**

* Kubernetes version - 1.14
* Using EKS (yes/no), if so version? yes
* AWS service targeted (S3, RDS, etc.) ECR

**Comment by nmvk** [comment]
Do see this for `ElastiCache` while deleting `CacheParameterGroup`

```
E0811 17:29:20.859097   35999 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 275 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x225e560, 0x2fd10b0)
        /Users/raghavnm/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /Users/raghavnm/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:48 +0x89
panic(0x225e560, 0x2fd10b0)
        /Users/raghavnm/sdk/go1.15rc1/src/runtime/panic.go:969 +0x175
github.com/aws/aws-controllers-k8s/pkg/runtime.(*reconciler).getOwnerAccountID(0xc000378c80, 0x0, 0x0, 0xc0008a2f69, 0x7)
        /Users/raghavnm/go/src/aws-controllers-k8s/pkg/runtime/reconciler.go:317 +0x22
github.com/aws/aws-controllers-k8s/pkg/runtime.(*reconciler).reconcile(0xc000378c80, 0xc0008a2f69, 0x7, 0xc0008a2f60, 0x9, 0x33306e60, 0x88ab73be1d13f)
        /Users/raghavnm/go/src/aws-controllers-k8s/pkg/runtime/reconciler.go:93 +0xd9
github.com/aws/aws-controllers-k8s/pkg/runtime.(*reconciler).Reconcile(0xc000378c80, 0xc0008a2f69, 0x7, 0xc0008a2f60, 0x9, 0x311fc51b2, 0xc0001dcab0, 0xc00057e908, 0xc00057e900)
        /Users/raghavnm/go/src/aws-controllers-k8s/pkg/runtime/reconciler.go:83 +0x57
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004fc300, 0x22b9b20, 0xc0008bdba0, 0x0)
        /Users/raghavnm/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256 +0x166
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004fc300, 0x203000)
        /Users/raghavnm/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0004fc300)
        /Users/raghavnm/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000669320)
        /Users/raghavnm/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000669320, 0x2636440, 0xc0003adf20, 0xc0005ad701, 0xc000357320)
        /Users/raghavnm/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000669320, 0x3b9aca00, 0x0, 0x1, 0xc000357320)
        /Users/raghavnm/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000669320, 0x3b9aca00, 0xc000357320)
        /Users/raghavnm/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /Users/raghavnm/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:193 +0x32d
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x2097242]
```
