### ISSUE TITLE
failure to generate API types for RDS

### ISSUE THREAD

**Issue by jaypipes** [aws/aws-controllers-k8s#89]
Getting failure when generating the API types for RDS:

```
jaypipes@thelio:~/go/src/github.com/aws/aws-controllers-k8s$ ./scripts/build-controller.sh rds
Building Kubernetes API objects for rds
Generating deepcopy code for rds
panic: interface conversion: types.Type is nil, not *types.Named

goroutine 1 [running]:
sigs.k8s.io/controller-tools/pkg/deepcopy.shouldBeCopied(0xc00029d7c0, 0xc0048a18c0, 0x403901)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/deepcopy/traverse.go:611 +0x35a
sigs.k8s.io/controller-tools/pkg/deepcopy.(*ObjectGenCtx).GenerateForPackage.func2(0xc0048a18c0)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/deepcopy/gen.go:226 +0xac
sigs.k8s.io/controller-tools/pkg/markers.EachType.func1(0xc000796500, 0xc0006ae700, 0xc0006be2a0)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/markers/zip.go:179 +0x779
sigs.k8s.io/controller-tools/pkg/loader.(*typeVisitor).Visit(0xc0047b8b80, 0xdf8160, 0xc0006be2a0, 0x0, 0x0)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/loader/visit.go:64 +0x140
go/ast.Walk(0xdf2780, 0xc0047b8b80, 0xdf8160, 0xc0006be2a0)
	/usr/local/go/src/go/ast/walk.go:52 +0x66
go/ast.Walk(0xdf2780, 0xc0047b8b80, 0xdf7ba0, 0xc0006ae700)
	/usr/local/go/src/go/ast/walk.go:331 +0xf3b
go/ast.walkDeclList(0xdf2780, 0xc0047b8b80, 0xc0007b4200, 0x18, 0x20)
	/usr/local/go/src/go/ast/walk.go:38 +0x9e
go/ast.Walk(0xdf2780, 0xc0047b8b80, 0xdf7a60, 0xc000796500)
	/usr/local/go/src/go/ast/walk.go:353 +0x264e
sigs.k8s.io/controller-tools/pkg/loader.EachType(0xc00029d7c0, 0xc0047b8b60)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/loader/visit.go:38 +0xaa
sigs.k8s.io/controller-tools/pkg/markers.EachType(0xc00029d7e0, 0xc00029d7c0, 0xc002ee0120, 0x8, 0xc0047cddc8)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/markers/zip.go:155 +0xa3
sigs.k8s.io/controller-tools/pkg/deepcopy.(*ObjectGenCtx).GenerateForPackage(0xc000af9b40, 0xc00029d7c0, 0xcd2acf, 0x5, 0xcd1e08)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/deepcopy/gen.go:216 +0x1da
sigs.k8s.io/controller-tools/pkg/deepcopy.Generator.Generate(0xc00009862b, 0x5d, 0x0, 0x0, 0xc0000a6140, 0xc0001ce701, 0xc0000a6140)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/deepcopy/gen.go:147 +0x1a5
sigs.k8s.io/controller-tools/pkg/genall.(*Runtime).Run(0xc00017d680, 0xc0001fa340)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/genall/genall.go:171 +0x15e
main.main.func1(0xc0001eb8c0, 0xc0001fa340, 0x2, 0x2, 0x0, 0x0)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/cmd/controller-gen/main.go:176 +0xa6
github.com/spf13/cobra.(*Command).execute(0xc0001eb8c0, 0xc000032190, 0x2, 0x2, 0xc0001eb8c0, 0xc000032190)
	/home/jaypipes/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:838 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001eb8c0, 0xc0001fa2e0, 0x4, 0x0)
	/home/jaypipes/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/home/jaypipes/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
main.main()
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/cmd/controller-gen/main.go:200 +0x34a
Building service controller for rds
```

I'm going to look into this and see what the deal is with the `types.Named` type.

**Comment by jaypipes** [comment]
@alina-kim well, this was a fun one to track down...

I ended up having to actually hack a local copy of `controller-gen` to output some debugging information while it processed the struct types in the RDS API v1alpha1 package:

```
jaypipes@thelio:~/go/src/github.com/aws/aws-controllers-k8s$ bash /home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/.run-controller-gen.sh object paths=./services/rds/apis/v1alpha1/...
XXXXX: Processing: CustomAvailabilityZoneSpec
XXXXX: Processing: CustomAvailabilityZoneStatus
XXXXX: Processing: CustomAvailabilityZone
XXXXX: Processing: CustomAvailabilityZoneList
XXXXX: Processing: DBClusterSpec
XXXXX: Processing: DBClusterStatus
XXXXX: Processing: DBCluster
XXXXX: Processing: DBClusterList
XXXXX: Processing: DBClusterEndpointSpec
XXXXX: Processing: DBClusterEndpointStatus
XXXXX: Processing: DBClusterEndpoint
XXXXX: Processing: DBClusterEndpointList
XXXXX: Processing: DBClusterParameterGroupSpec
XXXXX: Processing: DBClusterParameterGroupStatus
XXXXX: Processing: DBClusterParameterGroup
XXXXX: Processing: DBClusterParameterGroupList
XXXXX: Processing: DBClusterSnapshotSpec
XXXXX: Processing: DBClusterSnapshotStatus
XXXXX: Processing: DBClusterSnapshot
XXXXX: Processing: DBClusterSnapshotList
XXXXX: Processing: DBInstanceSpec
XXXXX: Processing: DBInstanceStatus
XXXXX: Processing: DBInstance
XXXXX: Processing: DBInstanceList
XXXXX: Processing: DBInstanceReadReplicaSpec
XXXXX: Processing: DBInstanceReadReplicaStatus
XXXXX: Processing: DBInstanceReadReplica
XXXXX: Processing: DBInstanceReadReplicaList
XXXXX: Processing: DBParameterGroupSpec
XXXXX: Processing: DBParameterGroupStatus
XXXXX: Processing: DBParameterGroup
XXXXX: Processing: DBParameterGroupList
XXXXX: Processing: DBProxySpec
XXXXX: Processing: DBProxyStatus
XXXXX: Processing: DBProxy
XXXXX: Processing: DBProxyList
XXXXX: Processing: DBSecurityGroupSpec
XXXXX: Processing: DBSecurityGroupStatus
XXXXX: Processing: DBSecurityGroup
XXXXX: Processing: DBSecurityGroupList
XXXXX: Processing: DBSnapshotSpec
XXXXX: Processing: DBSnapshotStatus
XXXXX: Processing: DBSnapshot
XXXXX: Processing: DBSnapshotList
XXXXX: Processing: DBSubnetGroupSpec
XXXXX: Processing: DBSubnetGroupStatus
XXXXX: Processing: DBSubnetGroup
XXXXX: Processing: DBSubnetGroupList
XXXXX: Processing: ActivityStreamMode
XXXXX: Processing: ActivityStreamStatus
XXXXX: Processing: ApplyMethod
XXXXX: Processing: AuthScheme
XXXXX: Processing: DBProxyStatus
panic: interface conversion: types.Type is nil, not *types.Named

goroutine 1 [running]:
sigs.k8s.io/controller-tools/pkg/deepcopy.shouldBeCopied(0xc00000ff40, 0xc00476bc80, 0x403901)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/deepcopy/traverse.go:613 +0x451
sigs.k8s.io/controller-tools/pkg/deepcopy.(*ObjectGenCtx).GenerateForPackage.func2(0xc00476bc80)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/deepcopy/gen.go:226 +0xac
sigs.k8s.io/controller-tools/pkg/markers.EachType.func1(0xc000434580, 0xc0007885c0, 0xc000188870)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/markers/zip.go:179 +0x779
sigs.k8s.io/controller-tools/pkg/loader.(*typeVisitor).Visit(0xc00465ddc0, 0xdf8000, 0xc000188870, 0x0, 0x0)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/loader/visit.go:64 +0x140
go/ast.Walk(0xdf2620, 0xc00465ddc0, 0xdf8000, 0xc000188870)
	/usr/local/go/src/go/ast/walk.go:52 +0x66
go/ast.Walk(0xdf2620, 0xc00465ddc0, 0xdf7a40, 0xc0007885c0)
	/usr/local/go/src/go/ast/walk.go:331 +0xf3b
go/ast.walkDeclList(0xdf2620, 0xc00465ddc0, 0xc00056c000, 0x18, 0x20)
	/usr/local/go/src/go/ast/walk.go:38 +0x9e
go/ast.Walk(0xdf2620, 0xc00465ddc0, 0xdf7900, 0xc000434580)
	/usr/local/go/src/go/ast/walk.go:353 +0x264e
sigs.k8s.io/controller-tools/pkg/loader.EachType(0xc00000ff40, 0xc00465dda0)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/loader/visit.go:38 +0xaa
sigs.k8s.io/controller-tools/pkg/markers.EachType(0xc00000ff60, 0xc00000ff40, 0xc003184b40, 0x8, 0xc0046b6aa8)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/markers/zip.go:155 +0xa3
sigs.k8s.io/controller-tools/pkg/deepcopy.(*ObjectGenCtx).GenerateForPackage(0xc002571b40, 0xc00000ff40, 0xcd2b2f, 0x5, 0xcd1e68)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/deepcopy/gen.go:216 +0x1da
sigs.k8s.io/controller-tools/pkg/deepcopy.Generator.Generate(0x0, 0x0, 0x0, 0x0, 0xc0000a80a0, 0xc00024e701, 0xc0000a80a0)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/deepcopy/gen.go:147 +0x1a5
sigs.k8s.io/controller-tools/pkg/genall.(*Runtime).Run(0xc000196c00, 0xc00027c300)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/genall/genall.go:171 +0x15e
main.main.func1(0xc00021fb80, 0xc00027c300, 0x2, 0x2, 0x0, 0x0)
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/cmd/controller-gen/main.go:176 +0xa6
github.com/spf13/cobra.(*Command).execute(0xc00021fb80, 0xc00011a160, 0x2, 0x2, 0xc00021fb80, 0xc00011a160)
	/home/jaypipes/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc00021fb80, 0xc00027c2a0, 0x4, 0x0)
	/home/jaypipes/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/jaypipes/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/jaypipes/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/cmd/controller-gen/main.go:200 +0x34a
exit status 2
```

Turns out there is a `DBProxyStatus` **Shape** in the RDS API. This name unfortunately conflicts with the top-level RDS `DBProxyStatus` struct type, which is the `DBProxy` CRD's `Status` field type.

So, I'm going to have to add some code into the type definition generator to watch for these overlapping names and rename them to something non-conflicting.
