### ISSUE TITLE
Unable to generate apigatewayv2 API (deepcopy-gen failure)

### ISSUE THREAD

**Issue by jaypipes** [aws/aws-controllers-k8s#94]
When attempting to generate the service controller for the APIGatewayV2 API, we're getting the following error:

```
panic: interface conversion: types.Type is nil, not *types.Named

goroutine 1 [running]:
sigs.k8s.io/controller-tools/pkg/deepcopy.shouldBeCopied(0xc000111120, 0xc0033f4180, 0x403901)
	/home/jaypipes/go/src/sigs.k8s.io/controller-tools/pkg/deepcopy/traverse.go:613 +0x451
sigs.k8s.io/controller-tools/pkg/deepcopy.(*ObjectGenCtx).GenerateForPackage.func2(0xc0033f4180)
	/home/jaypipes/go/src/sigs.k8s.io/controller-tools/pkg/deepcopy/gen.go:226 +0xac
sigs.k8s.io/controller-tools/pkg/markers.EachType.func1(0xc000882380, 0xc000728500, 0xc00078e060)
	/home/jaypipes/go/src/sigs.k8s.io/controller-tools/pkg/markers/zip.go:179 +0x779
sigs.k8s.io/controller-tools/pkg/loader.(*typeVisitor).Visit(0xc00315b2c0, 0xdf8000, 0xc00078e060, 0x0, 0x0)
	/home/jaypipes/go/src/sigs.k8s.io/controller-tools/pkg/loader/visit.go:64 +0x140
go/ast.Walk(0xdf2620, 0xc00315b2c0, 0xdf8000, 0xc00078e060)
	/usr/local/go/src/go/ast/walk.go:52 +0x66
go/ast.Walk(0xdf2620, 0xc00315b2c0, 0xdf7a40, 0xc000728500)
	/usr/local/go/src/go/ast/walk.go:331 +0xf3b
go/ast.walkDeclList(0xdf2620, 0xc00315b2c0, 0xc0000cb100, 0xc, 0x10)
	/usr/local/go/src/go/ast/walk.go:38 +0x9e
go/ast.Walk(0xdf2620, 0xc00315b2c0, 0xdf7900, 0xc000882380)
	/usr/local/go/src/go/ast/walk.go:353 +0x264e
sigs.k8s.io/controller-tools/pkg/loader.EachType(0xc000111120, 0xc00315b1c0)
	/home/jaypipes/go/src/sigs.k8s.io/controller-tools/pkg/loader/visit.go:38 +0xaa
sigs.k8s.io/controller-tools/pkg/markers.EachType(0xc000111140, 0xc000111120, 0xc001ce8e70, 0x8, 0xc00249db88)
	/home/jaypipes/go/src/sigs.k8s.io/controller-tools/pkg/markers/zip.go:155 +0xa3
sigs.k8s.io/controller-tools/pkg/deepcopy.(*ObjectGenCtx).GenerateForPackage(0xc002d27b40, 0xc000111120, 0xcd2b2f, 0x5, 0xcd1e68)
	/home/jaypipes/go/src/sigs.k8s.io/controller-tools/pkg/deepcopy/gen.go:216 +0x1da
sigs.k8s.io/controller-tools/pkg/deepcopy.Generator.Generate(0x0, 0x0, 0x0, 0x0, 0xc0001120a0, 0xc0001d6701, 0xc0001120a0)
	/home/jaypipes/go/src/sigs.k8s.io/controller-tools/pkg/deepcopy/gen.go:147 +0x1a5
sigs.k8s.io/controller-tools/pkg/genall.(*Runtime).Run(0xc000044680, 0xc000202340)
	/home/jaypipes/go/src/sigs.k8s.io/controller-tools/pkg/genall/genall.go:171 +0x15e
main.main.func1(0xc0001a5b80, 0xc000202340, 0x2, 0x2, 0x0, 0x0)
	/home/jaypipes/go/src/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go:176 +0xa6
github.com/spf13/cobra.(*Command).execute(0xc0001a5b80, 0xc000032190, 0x2, 0x2, 0xc0001a5b80, 0xc000032190)
	/home/jaypipes/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001a5b80, 0xc0002022e0, 0x4, 0x0)
	/home/jaypipes/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/jaypipes/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/jaypipes/go/src/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go:200 +0x34a
exit status 2
```

Since controller-tools' `deepcopy-gen` has virtually no debugging capability, I had to hack a local git clone of controller-tools up and re-ran the `deepcopy-gen` command with my local version to see what was going on:

```
jaypipes@thelio:~/go/src/github.com/aws/aws-controllers-k8s$ /home/jaypipes/go/src/sigs.k8s.io/controller-tools/.run-controller-gen.sh object paths=./services/apigatewayv2/apis/v1alpha1/...
XXX: Processing APISpec
XXX: Processing APIStatus
XXX: Processing API
XXX: Processing APIList
XXX: Processing APIMappingSpec
XXX: Processing APIMappingStatus
XXX: Processing APIMapping
XXX: Processing APIMappingList
XXX: Processing AuthorizerSpec
XXX: Processing AuthorizerStatus
XXX: Processing Authorizer
XXX: Processing AuthorizerList
XXX: Processing DeploymentSpec
XXX: Processing DeploymentStatus
XXX: Processing Deployment
XXX: Processing DeploymentList
XXX: Processing DomainNameSpec
XXX: Processing DomainNameStatus
XXX: Processing DomainName
XXX: Processing DomainNameList
XXX: Processing AuthorizationType
XXX: Processing AuthorizerType
XXX: Processing ConnectionType
XXX: Processing ContentHandlingStrategy
XXX: Processing DeploymentStatus_SDK
XXX: Processing DomainNameStatus_SDK
XXX: Processing EndpointType
XXX: Processing IntegrationType
XXX: Processing LoggingLevel
XXX: Processing PassthroughBehavior
XXX: Processing ProtocolType
XXX: Processing SecurityPolicy
XXX: Processing VPCLinkStatus_SDK
XXX: Processing VPCLinkVersion
XXX: Processing IntegrationSpec
XXX: Processing IntegrationStatus
XXX: Processing Integration
XXX: Processing IntegrationList
XXX: Processing IntegrationResponseSpec
XXX: Processing IntegrationResponseStatus
XXX: Processing IntegrationResponse
XXX: Processing IntegrationResponseList
XXX: Processing ModelSpec
XXX: Processing ModelStatus
XXX: Processing Model
XXX: Processing ModelList
XXX: Processing RouteSpec
XXX: Processing RouteStatus
XXX: Processing Route
XXX: Processing RouteList
XXX: Processing RouteResponseSpec
XXX: Processing RouteResponseStatus
XXX: Processing RouteResponse
XXX: Processing RouteResponseList
XXX: Processing StageSpec
XXX: Processing StageStatus
XXX: Processing Stage
XXX: Processing StageList
XXX: Processing API
<ERROR OUTPUT>
```

Previous fix for #89 only fixed Enum types apparently and not TypeDef types that have conflicting names with CRDs. In the case of the APIGatewayV2 API, there is a `Shape` called `API` that is conflicting with the top-level resource name (the CRD's `Kind`) of `API` :(

**Comment by jaypipes** [comment]
Yep, sure enough, there is a `aws-sdk-go/private/model/api.Shape` with the name `Api` that has the following definition:

```json
    "Api" : {
      "type" : "structure",
      "members" : {
        "ApiEndpoint" : {
          "shape" : "__string",
          "locationName" : "apiEndpoint"
        },
        "ApiId" : {
          "shape" : "Id",
          "locationName" : "apiId"
        },
        "ApiKeySelectionExpression" : {
          "shape" : "SelectionExpression",
          "locationName" : "apiKeySelectionExpression"
        },
        "CorsConfiguration" : {
          "shape" : "Cors",
          "locationName" : "corsConfiguration"
        },
        "CreatedDate" : {
          "shape" : "__timestampIso8601",
          "locationName" : "createdDate"
        },
        "Description" : {
          "shape" : "StringWithLengthBetween0And1024",
          "locationName" : "description"
        },
        "DisableSchemaValidation" : {
          "shape" : "__boolean",
          "locationName" : "disableSchemaValidation"
        },
        "ImportInfo" : {
          "shape" : "__listOf__string",
          "locationName" : "importInfo"
        },
        "Name" : {
          "shape" : "StringWithLengthBetween1And128",
          "locationName" : "name"
        },
        "ProtocolType" : {
          "shape" : "ProtocolType",
          "locationName" : "protocolType"
        },
        "RouteSelectionExpression" : {
          "shape" : "SelectionExpression",
          "locationName" : "routeSelectionExpression"
        },
        "Tags" : {
          "shape" : "Tags",
          "locationName" : "tags"
        },
        "Version" : {
          "shape" : "StringWithLengthBetween1And64",
          "locationName" : "version"
        },
        "Warnings" : {
          "shape" : "__listOf__string",
          "locationName" : "warnings"
        }
      },
      "required" : [ "RouteSelectionExpression", "Name", "ProtocolType" ]
    },
```

It is returned in the `ListApis` Operation, whose return shape (called "__listOfApi" is a list of `Api` shapes:

```json
    "__listOfApi" : {
      "type" : "list",
      "member" : {
        "shape" : "Api"
      }
    },
```
